### ISSUE TITLE
No service for type 'Rollbar.AspNetCore.RollbarLoggerProvider' has been registered.

### ISSUE THREAD

**Issue by ricardoalcantara** [rollbar/Rollbar.NET#110]
Hi I am having problem using rollbar

OS: Ubuntu 16.04
```
$ dotnet --version
2.1.4
```

```
Application startup exception: System.InvalidOperationException: No service for type 'Rollbar.AspNetCore.RollbarLoggerProvider' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.ApplicationBuilderExtensions.UseRollbarMiddleware(IApplicationBuilder builder)
   at nuget_error.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /home/anyuser/Projects/ext/nuget_error/Startup.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Unhandled Exception: crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.InvalidOperationException: No service for type 'Rollbar.AspNetCore.RollbarLoggerProvider' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.ApplicationBuilderExtensions.UseRollbarMiddleware(IApplicationBuilder builder)
   at nuget_error.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /home/anyuser/Projects/ext/nuget_error/Startup.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
System.InvalidOperationException: No service for type 'Rollbar.AspNetCore.RollbarLoggerProvider' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.ApplicationBuilderExtensions.UseRollbarMiddleware(IApplicationBuilder builder)
   at nuget_error.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in /home/anyuser/Projects/ext/nuget_error/Startup.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at nuget_error.Program.BuildWebHost(String[] args) in /home/anyuser/Projects/ext/nuget_error/Program.cs:line 21
   at nuget_error.Program.Main(String[] args) in /home/anyuser/Projects/ext/nuget_error/Program.cs:line 17
```
this repository has a 'not working' sample:
https://github.com/ricardoalcantara/rollbad_sample

It was working before but for some reason I don't understand it's not working anymore.

**Comment by akornich** [comment]
@ricardoalcantara, let me restate the problem - just to make sure i understand it correctly. You are saying v1.0.3 used to work fine on both Windows and Ubuntu. After upgrading to v1.1.0, it works on Windows but does not work on Ubuntu. When rolled back to 1.0.3 on Ubuntu, it still does not work. Correct?
Did you try refreshing .NET Core installation on Ubuntu?

**Comment by akornich** [comment]
@ricardoalcantara, i just looked into the sample app you posted on GitHub and it looks like you need to update your ConfigureServices(...) method in Startup.cs to look like this (to register the RollbarLogger service):

        public void ConfigureServices(IServiceCollection services)
        {
            RollbarLocator
            .RollbarInstance
            // minimally required Rollbar configuration:
            .Configure(new RollbarConfig("123")
            {
                Environment = "Development",
            })
            // optional step if you would like to monitor Rollbar internal events within your application:
            // .InternalEvent += OnRollbarInternalEvent
            // .InternalEvent += (sender, e) => { Console.WriteLine(e.TraceAsString()); };
            ;

            services.AddRollbarLogger(loggerOptions =>
            {
                loggerOptions.Filter = (loggerName, loglevel) => loglevel >= LogLevel.Trace;
            });

            services.AddMvc();
        }

**Comment by ricardoalcantara** [comment]
@akornich Thank you for your replay, this change is not documented, isn't it? I read the documentation many times yesterday and I didn't find it.

**Comment by ricardoalcantara** [comment]
I also thing that you could let `services.AddRollbarLogger()` be empty with something default like
```
services.AddRollbarLogger(loggerOptions =>
{
        loggerOptions.Filter = (loggerName, loglevel) => true;
});
// same as
services.AddRollbarLogger();
```

**Comment by akornich** [comment]
@ricardoalcantara, absolutely. thanks for the suggestion. we will add it the upcoming release (most likely sometime towards the end of this week).
i already have a bug #111 filed to update the documentation today.

**Comment by ricardoalcantara** [comment]
Thank you.
