### ISSUE TITLE
Not able to run xamarine sample app with Rollbar Notifier.

### ISSUE THREAD

**Issue by RollbarExample** [rollbar/Rollbar.NET#131]
Hi,
I am not able to run the xamarine sample application with Rollbar notifier that you have provided.
Following are the observations -
1. Cloned the sample application from here.
  https://github.com/rollbar/Rollbar.NET/tree/master/Sample.Xamarin.Forms
2. Application is working fine if i am running without installing Rollbar.
3. When i am trying run after installing Rollbar through Nuget. It is throwing error in the debug/release mode.

Below are the both error log.
Debug-
```
04-26 18:33:31.251 D/Mono( 5851): Assembly Loader probing location: 'System.Buffers'.
04-26 18:33:31.251 F/monodroid-assembly( 5851): Could not load assembly 'System.Buffers' during startup registration.
04-26 18:33:31.251 F/monodroid-assembly( 5851): This might be due to an invalid debug installation.
04-26 18:33:31.252 F/monodroid-assembly( 5851): A common cause is to 'adb install' the app directly instead of doing from the IDE.
Thread started: <Thread Pool> #4
Debugger Connection Lost: Debugger lost connection to the running application. Likely this means the application terminated unexpectedly.
```
Release-
```
1>Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
1>   at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName) in E:\A\_work\30\s\External\androidtools\Mono.AndroidTools\Internal\AdbOutputParsing.cs:line 333
1>   at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass94_0.<InstallPackage>b__0(Task`1 t) in E:\A\_work\30\s\External\androidtools\Mono.AndroidTools\AndroidDevice.cs:line 746
1>   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
1>   at System.Threading.Tasks.Task.Execute()
1>Done building project "Sample.Xamarin.Forms.Android.csproj".
1>Build succeeded.
1>Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
1>   at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName) in E:\A\_work\30\s\External\androidtools\Mono.AndroidTools\Internal\AdbOutputParsing.cs:line 333
1>   at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass94_0.<InstallPackage>b__0(Task`1 t) in E:\A\_work\30\s\External\androidtools\Mono.AndroidTools\AndroidDevice.cs:line 746
1>   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
1>   at System.Threading.Tasks.Task.Execute()
1>
1>Deploy failed on Android_Accelerated_x86_Nougat
```

Could you please help me out?

Thanks and Regards.

Wahid Ali.

**Comment by akornich** [comment]
@RollbarExample, i am working on this problem. So far, not much progress. At some point I was able to repro the problem by tweaking  Android SDK targets and emulators, but not anymore. I'll spend a couple of more hour on this one. If I do not get any deterministic resolution, I'll just check in what I have now and let you try it on your side.

**Comment by akornich** [comment]
@RollbarExample, i am giving up on this one for now. it seems to be some kind of nuget packaging issue for xamarin-on-android projects. clearly, the same shared xamarin project that uses Rollbar.NET notifier works fine under xamarin-on-ios and xamarin-on-uwp with no problem. if you look at links below,  people are reporting virtually identical problem outside of any Rollbar context and some allegetly were able to resolve it clearing and reinstalling android nuget packages (however, it did not work for me). i'll get back to this item in a few days once i complete other more critical tasks. 

[https://stackoverflow.com/questions/49297409/could-not-load-assembly-system-buffers-during-startup-registration](url)
[https://developercommunity.visualstudio.com/content/problem/152947/xamarin-android-run-error-could-not-load-assembly.html](url)
[https://forums.xamarin.com/discussion/113718/android-error-with-signalr-core-could-not-load-assembly-system-memory-during-startup-registration](url)

**Comment by akornich** [comment]
@RollbarExample , is this one still an issue? Or the provided links gave some clues?

**Comment by cwrea** [comment]
I came across this issue with a keyword search for issues similar to [an issue I was having with Xamarin.Android](https://github.com/xamarin/xamarin-android/issues/1769). Might be worth retrying with Visual Studio 15.7.3 update (just came out). If 15.7.3 doesn't fix this issue too, I suggest opening an issue for [Xamarin.Android](https://github.com/xamarin/xamarin-android/).

**Comment by akornich** [comment]
@cwrea, thanks for the info. i shall try it tomorrow.

**Comment by RollbarExample** [comment]
@akornich I have tried with the suggested link but did not get any luck. I have observed that the problem is coming with your example app. I am able to run and build if am creating the fresh Xamarine app.

**Comment by akornich** [comment]
@cwrea, thanks a lot! Upgrading Visual Studio to 15.7.3 solved the problem. However, I also had to add following settings to the Android project file to resolve newly introduced deployment issues (I assume they are a result of the VS upgrade since I did not see those before):
    <AndroidSupportedAbis />
    <AndroidCreatePackagePerAbi>true</AndroidCreatePackagePerAbi>
