### ISSUE TITLE
Error using the log4net plugin in WPF application

### ISSUE THREAD

**Issue by shmulyeng** [rollbar/Rollbar.NET#249]
`log4net:ERROR Could not create Appender [rollbar] of type [Rollbar.PlugIns.Log4net.RollbarAppender, Rollbar.PlugIns.Log4net]. Reported error follows.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Rollbar.Common.ReconfigurableBase`2.Reconfigure(TBase likeMe)
   at Rollbar.RollbarConfig.Reconfigure(IRollbarConfig likeMe)
   at Rollbar.RollbarConfig.Rollbar.Common.IReconfigurable<Rollbar.IRollbarConfig,Rollbar.IRollbarConfig>.Reconfigure(IRollbarConfig likeMe)
   at Rollbar.RollbarLogger.Rollbar.IRollbar.Configure(IRollbarConfig settings)
   at Rollbar.RollbarFactory.CreateProper(IRollbarConfig rollbarConfig, Nullable`1 rollbarBlockingLoggingTimeout, IAsyncLogger& rollbarAsyncLogger, ILogger& rollbarLogger)
   at Rollbar.PlugIns.Log4net.RollbarAppender..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.ParseAppender(XmlElement appenderElement)`

After digging through the source code, the following function looks like the issue.
File: NetFramework/RollbarConfigSection.cs

`        public static RollbarConfigSection GetConfiguration()
        {
            RollbarConfigSection configuration =
                ConfigurationManager.GetSection("rollbar") 
                as RollbarConfigSection;
            return null;
        }`

The function is returning null in all cases. I tested the GetSection function in my code and it's returning the correct section.

**Comment by akornich** [comment]
@shmulyeng , there is already a fix for an issue like this one. We will be making a release (that includes the fix) on December 26th. If you would like to try the fix sooner - it is available here:
[https://github.com/WideSpectrumComputing/Rollbar.NET](https://github.com/WideSpectrumComputing/Rollbar.NET)
