### ISSUE TITLE
Rollbar .NET in WPF application

### ISSUE THREAD

**Issue by cwebster** [rollbar/Rollbar.NET#29]
Is this possible?

I have the following code:

```
//Initialize Rollbar
Rollbar.Init(newRollbarConfig
{
AccessToken = "0dbfbfea85a245f79d2f4a1600b8f552",
#if DEBUG
Environment = "development"
#else
Environment = "production"
#endif 
});
AppDomain.CurrentDomain.UnhandledException += (sender, args) =>
{
Rollbar.Report(args.ExceptionObject as System.Exception);
};
Rollbar.Report("Started application + " + Settings.Default.Client, ErrorLevel.Info);
```

On deploying to the users systems I get the following exception
```
Application: ReferralLaboratories.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.WebException
at System.Net.WebClient.UploadDataInternal(System.Uri, System.String, Byte[], System.Net.WebRequest ByRef)
at System.Net.WebClient.UploadString(System.Uri, System.String, System.String)
at System.Net.WebClient.UploadString(System.Uri, System.String)
at RollbarDotNet.RollbarClient.SendPost[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, System.__Canon)
at RollbarDotNet.RollbarClient.PostItem(RollbarDotNet.Payload)
at RollbarDotNet.Rollbar.SendBody(RollbarDotNet.Body, System.Nullable`1<RollbarDotNet.ErrorLevel>, System.Collections.Generic.IDictionary`2<System.String,System.Object>)
at RollbarDotNet.Rollbar.Report(System.String, System.Nullable`1<RollbarDotNet.ErrorLevel>, System.Collections.Generic.IDictionary`2<System.String,System.Object>)
at Referral_Laboratories.App..ctor()
at Referral_Laboratories.App.Main()
```

**Comment by rokob** [comment]
I am not sure why you are getting the WebException here, it could be due to a bad access token that the server is rejecting, it could also be that the payload somehow is not being converted to a json string correctly and either it ends up null or the server is rejecting it. Do you have any more information on what the final payload is that is being sent? Are you sure you can make post requests with that access token independently of this library, i.e. could it be a network issue? We are working on a new release of this library which will be tracked here https://github.com/rollbar/Rollbar.NET/milestone/1 and we will make sure that any WebExceptions that would otherwise get thrown are handled and provide better diagnostic information.

**Comment by akornich** [comment]
I believe the exception is caused by either a network connectivity problem or a service side problem. Most likely, it has nothing to do with the Rollbar.NET notifier itself.
Here are some reference to explore:   
[https://msdn.microsoft.com/en-us/library/system.net.webexception(v=vs.110).aspx](url)
[https://msdn.microsoft.com/en-us/library/48ww3ee9.aspx](url)
[https://airbrake.io/blog/dotnet-exception-handling/system-net-webexception](url)

Rollbar.NET v1 has a built in instrumentation that allows monitoring all the connectivity and notifier internal issues/errors (if any) by the hosting application itself.
