### ISSUE TITLE
System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Internal.BufferingHelper' from assembly 'Microsoft.AspNetCore.Http, Version=3.0.0.0

### ISSUE THREAD

**Issue by claytondus** [rollbar/Rollbar.NET#479]
Rollbar.NetCore.AspNet 3.6.2

In an ASP.NET Core 3.0 app with UseRollbarMiddleware enabled, upon receiving the first request the following exception is thrown:

```
System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Internal.BufferingHelper' from assembly 'Microsoft.AspNetCore.Http, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Rollbar.NetCore.AspNet.RollbarMiddleware.Invoke(HttpContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Rollbar.NetCore.AspNet.RollbarMiddleware.Invoke(HttpContext context)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 104
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

I believe this is related to [this issue](https://github.com/aspnet/AspNetCore/issues/12505 ), where the call to ```EnableRewind()``` in ```Rollbar.NetCore.AspNet/RollbarMiddleware.cs``` should be replaced by ```EnableBuffering()```.  This call does not exist prior to ASP.NET Core 2.1, but all previous versions are EOL now.

**Comment by akornich** [comment]
@claytondus , thanks for reporting this and for the initial research of the problem! Much appreciated!
I'll try to get a fix in ASAP.
