### ISSUE TITLE
Periodic connectivity/stability issues with Rollbar.NET/Rollbar's API

### ISSUE THREAD

**Issue by kieranbenton** [rollbar/Rollbar.NET#489]
**Describe the bug**
We've been seeing intermittent (but periodic and not isolated) errors reported from Rollbar.NET that it is unable to communicate with the Rollbar API. We have only noticed these recently since we upgraded our applications to report rollbar internal events to our logs - and then we had a client report an issue that we should have seen a rollbar for, but did not.

They are manifesting themselves as ```502 Bad Gateway``` issues by the looks of the logs.

Not sure who I should reporting this to as we are paying customers of Rollbar - but thought I'd head here first! :-)

The errors we are seeing look like this (repeated ```CommunicationErrorEventArgs``` followed by a ```PayloadDropEventArgs```):
```
2020-01-10T10:59:08.688224717Z 2020-01-10 10:59:08,687 FATAL  {IRollbar} Unable to talk to rollbar
2020-01-10T10:59:08.688291469Z 01/10/2020 10:59:08 +00:00 - CommunicationErrorEventArgs:
2020-01-10T10:59:08.688296743Z   RollbarConfig:
2020-01-10T10:59:08.688300688Z     AccessToken: xxx
2020-01-10T10:59:08.688304661Z     EndPoint: https://api.rollbar.com/api/1/
2020-01-10T10:59:08.688308448Z     ScrubFields: System.String[]
2020-01-10T10:59:08.688326904Z     ScrubWhitelistFields: System.String[]
2020-01-10T10:59:08.688331624Z     Enabled: True
2020-01-10T10:59:08.688335461Z     Environment: Production
2020-01-10T10:59:08.688339176Z     Server: Rollbar.DTOs.Server
2020-01-10T10:59:08.688342892Z     Person: 
2020-01-10T10:59:08.688346539Z     ProxyAddress: 
2020-01-10T10:59:08.688350350Z     MaxReportsPerMinute: 
2020-01-10T10:59:08.688354214Z     ReportingQueueDepth: 20
2020-01-10T10:59:08.688357957Z     MaxItems: 0
2020-01-10T10:59:08.688361642Z     CaptureUncaughtExceptions: True
2020-01-10T10:59:08.688380500Z     IpAddressCollectionPolicy: Collect
2020-01-10T10:59:08.688384733Z     PersonDataCollectionPolicies: None
2020-01-10T10:59:08.688410305Z   Payload: ...
2020-01-10T10:59:08.688437798Z   RetriesLeft: 0
2020-01-10T10:59:08.688442044Z   Error: System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 502 (Bad Gateway).)
2020-01-10T10:59:08.688446154Z  ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
 at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
 at Rollbar.RollbarClient.PostAsJsonAsync(PayloadBundle payloadBundle)
2020-01-10T10:59:08.688458813Z    --- End of inner exception stack trace ---
2020-01-10T10:59:08.688462919Z    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
2020-01-10T10:59:08.688466947Z    at Rollbar.RollbarQueueController.Process(PayloadQueue queue, RollbarResponse& response)
2020-01-10T10:59:08.688471123Z  : correlationIds = [session = , ip = , request = ]

... repeated ...

2020-01-10T10:59:08.689570099Z 2020-01-10 10:59:08,689 FATAL  {IRollbar} Unable to talk to rollbar
2020-01-10T10:59:08.689616671Z 01/10/2020 10:59:08 +00:00 - PayloadDropEventArgs:
2020-01-10T10:59:08.689621702Z   RollbarConfig:
2020-01-10T10:59:08.689625722Z     AccessToken: xxx
2020-01-10T10:59:08.689629633Z     EndPoint: https://api.rollbar.com/api/1/
2020-01-10T10:59:08.689633451Z     ScrubFields: System.String[]
2020-01-10T10:59:08.689637291Z     ScrubWhitelistFields: System.String[]
2020-01-10T10:59:08.689641217Z     Enabled: True
2020-01-10T10:59:08.689644971Z     Environment: Production
2020-01-10T10:59:08.689648828Z     Server: Rollbar.DTOs.Server
2020-01-10T10:59:08.689652614Z     Person: 
2020-01-10T10:59:08.689656416Z     ProxyAddress: 
2020-01-10T10:59:08.689660133Z     MaxReportsPerMinute: 
2020-01-10T10:59:08.689663981Z     ReportingQueueDepth: 20
2020-01-10T10:59:08.689690843Z     MaxItems: 0
2020-01-10T10:59:08.689695281Z     CaptureUncaughtExceptions: True
2020-01-10T10:59:08.689699349Z     IpAddressCollectionPolicy: Collect
2020-01-10T10:59:08.689712401Z     PersonDataCollectionPolicies: None
2020-01-10T10:59:08.689718215Z   Payload: ...
2020-01-10T10:59:08.689737687Z   Drop Reason: AllTransmissionRetriesFailed
2020-01-10T10:59:08.689741643Z  : correlationIds = [session = , ip = , request = ]
``` 

I'm having several of our applications report these Rollbar.NET events using this:
```
// make sure we listen for any internal issues in rollbar and at least log them locally
RollbarLocator.RollbarInstance.InternalEvent += new EventHandler<RollbarEventArgs>((sender, e) =>
{
	string trace = e.TraceAsString();

	switch (e)
	{
		case RollbarApiErrorEventArgs apiErrorEvent:
		case CommunicationErrorEventArgs communicationErrorEvent:
		case InternalErrorEventArgs internalErrorEvent:
		case PayloadDropEventArgs payloadDropEventArgs:
			log.Fatal("Unable to talk to rollbar" + Environment.NewLine + trace);
			break;

		default: throw new NotImplementedException();
	}
});
```

To be clear these internal failures we are seeing are occuring accross *multiple applications* we deploy into GKE, on *multiple nodes* and we are also most of the time successfully receiving rollbars from these applications - so its not that all rollbar's reports are being blocked by a firewall etc. Our applications reach out to other external services and we're not seeing any issues talking to them either.

Our applications are under low but steady load throughout the day - and I don't see any correlation between load on our systems and occurrence of the issue. To give you an idea, scraping our Stackdriver Logs there is the following distribution for the last few days:

```
10th: 10:45 - 10:59 (approximately 12 errors)
9th: 12:00 - 12:33 (approximately 14 errors)
8th: 15:11 - 16:53 (approximately 27 errors)
```

**To Reproduce**
Unfortunately no hard steps to reproduce, as discussed above it doesnt seem correlated to time or load.

**Expected behavior**
Rollbar.NET to successfully push all errors to the API.

**Screenshots**
![image](https://user-images.githubusercontent.com/39090/72156294-1dc48a80-33ad-11ea-8558-e2f3126525b7.png)

Can provide more on request (but will need to redact keys etc).

**Rollbar Client - Rollbar.NET Hosting Environment (please complete the following information):**
 - Rollbar.NET Host type: All ASP.NET Core 3.1: MVC app, MVC API app, worker app
 - OS and its version: Linux 4.15.0-1044-gke 46-Ubuntu SMP Fri Sep 13 15:02:00 UTC 2019
 - .NET flavor and its version: .NET Core 3.1 
 - Rollbar.NET Version: currently 3.5.0 want to try 3.6.3 but was blocked by https://github.com/rollbar/Rollbar.NET/issues/485
 - Applicable Rollbar Plug-in (if any): none
 - Applicable custom third party logging library/framework integration (if any): We use log4net currently - but its not integrated with Rollbar.
 - Applicable Browser (if any): N/A

**Comment by kieranbenton** [comment]
Anything else I can do to help run this down/diagnose the problem please just shout. I'm going to try and upgrade to the latest Rollbar version today now that https://github.com/rollbar/Rollbar.NET/issues/485 is reported fixed - so will follow up after that as well.

**Comment by kieranbenton** [comment]
Apologies just renamed this from "Periodic connectivity/stability issues with Rollbar.NET/Rollbar's API - only appeared since upgrading from .NET Core 2.2 to 3.1" since I originally thought that was implicated - since I only started seeing errors once that release was in production.

After some more investigation though - I realised it was only in that release I started logging the events at all! So it doesnt look to be related.

**Comment by akornich** [comment]
@kieranbenton, i am looking into it in detail. However, based on the initial overview of the problem and taking into account that we classify the errors as communication error events, it already tells me that most likely a sort of communication/networking instability problem that does not have anything to do directly with the SDK. Give me some more time to look deeper into it...

**Comment by akornich** [comment]
@kieranbenton ,  according to [this article](https://www.lifewire.com/502-bad-gateway-error-explained-2622939) the 502 response error could be a result of a basic networking infrastructure problem triggered by multiple links in the networking connectivity chain. I already contacted our API services devops to verify if we are having any sorts of these issues on our side (however as of now, there is no known outstanding issue related to 502). I'll keep you updated on their findings (if any).

**Comment by kieranbenton** [comment]
@akornich thanks for getting someone to look at it from your side. 

Under normal circumstances I would be skeptical myself that there is something wrong on your side, and because of that I've had our systems engineer look at all of the other outbound traffic we perform and we've not had any issues. Like I said we're using GKE in Google Cloud (in a relatively standard configuration) so its not some hand rolled infrastructure - we've also not changed anything for a couple of months, and even longer than that network wise.

Its also pretty strange that its only in the last few weeks that we've noticed that some clients have been having issues (that we've logged locally) but which haven't made their way to Rollbar - so I would appreciate you guys being thorough - right now it feels like it might be an issue on your end to me or somewhere in between Google Cloud and yourselves.

Have a great weekend!

**Comment by akornich** [comment]
hi @kieranbenton , i got an update from our backend and dev-ops engineers:

We’ve identified the issue causing these intermittent 502s. Overall it accounts for 0.01% of requests (99.99% of requests are accepted). We want this to be better, too, and our team is working on a project that will eliminate this class of 502s; we are aiming to have it solved by the end of Q1 2020.
In the meantime, we would like to confirm with you that when these 502s occur, there is no impact on your application’s availability - i.e. the only impact of the 502s is that those events are dropped by the Rollbar API. 

Additionally, we’d like to highlight that the latest release of Rollbar.NET has these features that could possibly mitigate this issue for now:
1. local payload logging (via RollbaTraceSource/Listener)
2. By tapping into Rollbar internal events infrastructure (https://docs.rollbar.com/docs/dotnet#section-monitoring-the-notifiers-internal-events).

**Comment by akornich** [comment]
i am closing this item since there is nothing we can do on the SDK side to address it. the backend team has an internal work item dedicated to this issue...
